---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        name: redis
        ports:
        - containerPort: 6379
...
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gin-redis
  name: gin-redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gin-redis
  template:
    metadata:
      labels:
        app: gin-redis
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: shubhamtatvamasi/gin-redis
        name: gin-redis
        imagePullPolicy: Always
        startupProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: GIN_MODE
          value: "release"
...
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gin-redis
  name: gin-redis
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  type: NodePort
  selector:
    app: gin-redis
...
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gin-redis
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gin-redis
  targetCPUUtilizationPercentage: 10
...
